### ISSUE TITLE
Consolidating the data failed

### ISSUE THREAD

**Issue by simongis** [Esri/elevation-gp-python#1]
I have followed the steps in the wiki to prep the data and publish the GP service to our federated 10.4 ArcGIS Server that also includes ArcGIS Data Store.

Only have two mosaic datasets.
Believe I have followed the guide correctly and tool works fine in ArcMap.  Fails to publish to Server with the ['Consolidating the data failed'](http://resources.arcgis.com/en/help/main/10.1/index.html#//00vp0000002r001270) error. 

Any ideas how to troubleshoot this further?  Can't see anything obvious in the ArcGIS Server logs either. 

![failtopublish](https://cloud.githubusercontent.com/assets/2769383/15006988/50d8d38c-1218-11e6-8c54-25587c2fdd5d.gif)

**Comment by xwang2** [comment]
The data could be too large. Did you register your data on Server? Please see the help doc in the package (the PDF file) for steps on how to move data to the server and register it.

**Comment by simongis** [comment]
Data is on the server.  The folder has been registered with the Server.  The animated GIF is all from the Server machine itself.  At the end of the animation it shows the registered data stores.  There is no 'copying data to server' going on here.  

Any other ideas?

**Comment by simongis** [comment]
Have also replicated on the Esri 10.4 AMI template for WebGIS on a single machine.  Same error - 'failed to create a service definition' in the GUI, 'Consolidating the data failed' in the GP results panel.  It happens after 256k has been transferred.

**Comment by xwang2** [comment]
The data folder registration seems to be OK from what is showing in the video capture. After looking at some online help for this error, there are several reasons that could lead to this error:
1. Desktop license level. Try a higher license.
2. Low disk space or stage path is too long. Try changing the stage path.
http://resources.arcgis.com/en/help/main/10.1/index.html#//00vp0000002r001270

**Comment by simongis** [comment]
1. Using an advanced Desktop license with NA/SA extensions.
2. Plenty of disk space, staging path set to D:\data

Tricky one.  Ill do some more troubleshooting, but as I have replicated on two setups now, the latter one being the cloudfront template from Esri for a WebGIS on a single machine, I am at a loss on what the cause could be.  Should also point out that other services are publishing fine.

**Comment by xwang2** [comment]
Fixed. Please get the updated ElevationTools.pyt.

**Comment by xwang2** [comment]
Fixed. Please get the updated ElevationTools.pyt.

**Comment by paulamaddock** [comment]
What was the solution to this?  I am having the exact same issue except my gptool isn't reading from a layer in the mxd from which it is being published and there are now layers in the service.  All data used as parameters' data sources are registered with the server.

**Comment by Balmark** [comment]
> All data used as parameters' data sources are registered with the server.

Hey @paulamaddock  .. I had something similar, I had some text in my toolbox python script that was 'c:\...\some folders\etc\.....' but wasn't being used anywhere. However, it appears when I went to publish, it was trying to include this folder.. I found this out by starting the publish, then spamming a copy of the folder from the
C:\Users\<user>\AppData\Local\ESRI\Desktop10.6\Staging\<server>\0 
to another (to catch it before it deleted it on the failed attempt) using xcopy

Inside there I saw references to files+folders it shouldn't have been including..

I removed these and now my export wasn't going over some sizelimit and was publishing ok
(I know it's a late response, but might help someone)
